#!/bin/bash
# Copyright 2019 Darius Neatu (neatudarius@gmail.com)

sudo apt-get update

sudo apt-get install                        \
    build-essential                         \
    gcc                                     \
    python2.7 python-dev  python-pip        \
    python3   python3-dev python3-pip       \
    make gdb valgrind                       \


# upgrade setup tools package
sudo pip install --upgrade setuptools
sudo pip3 install --upgrade setuptools

# all py packages json os pathlib recordclass subprocess sys
sudo pip3 install                           \
    argparse                                \
    pathlib                                 \
    recordclass                             \
